apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-spring-boot-docker
  labels:
    app: kotlin-spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotlin-spring-boot-docker
  template:
    metadata:
      labels:
        app: kotlin-spring-boot-docker
    spec:
      containers:
        - name: kotlin-spring-boot-docker
          image: m1kah/kotlin-spring-boot-docker:1.0.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kotlin-spring-boot-docker
spec:
  selector:
    app: kotlin-spring-boot-docker
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  type: LoadBalancer

